# Generated by Django 4.2.13 on 2024-09-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_user_cart_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
