# Generated by Django 4.2.13 on 2024-09-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
        ('cart', '0004_rename_username_cart_user_remove_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
